### ISSUE TITLE
무한스크롤 반복 오류

### ISSUE THREAD

**Issue by seob7** [KNUTICE/KNUTICE-iOS#13]
# Issue : 무한스크롤 반복 오류

## Description
현재 서버에서 무한스크롤 `Cursor` 방식을 `contentNumber` 에서 `nttId` 로 변경하였으나, 클라이언트(앱)에서 해당 변경 사항이 아직 반영되지 않아 동일한 게시물이 반복적으로 표시되는 문제가 발생하고 있습니다.

## Cause
서버의 페이징 방식이 `contentNumber` 에서 `nttId` 로 변경되었으나, 클라이언트가 기존 로직을 사용하여 데이터 요청을 하고 있어 발생하는 문제.

## Solution
앱의 로직을 최신 서버의`nttId` 기반 방식에 맞춰 수정해야 합니다.
앱 업데이트 후 정상적인 동작 확인할 필요가 있습니다.

![스크린샷 2024-09-20 오전 1 13 37](https://github.com/user-attachments/assets/26889f8f-12e3-47bf-a3bb-ae911786d5e2)![스크린샷 2024-09-20 오전 1 13 46](https://github.com/user-attachments/assets/698f8102-5f0f-4ed4-834c-ce4d06cc675b)

**Comment by jeongHunE** [comment]
1.1.0 beta 2에서 수정 완료
