### ISSUE TITLE
스크롤시, 마지막 공지 스크롤 후에 무한 로딩 화면이 그대로 남아있는 현상

### ISSUE THREAD

**Issue by ITSTIME1** [KNUTICE/KNUTICE-iOS#16]
## Issue : 공지당 마지막 무한 스크롤시, 스크롤 표시가 계속 남아있는 현상
마지막 공지를 받아오는 스크롤시, 아래 화면과 같이 인디케이터(?)가 계속 남아 있는 현상이 있습니다.
위 아래로 스크롤을 다시 해봤지만, 여전히 스크롤 표시가 계속 남아 있습니다. 

해당 문제에 대해서, 개선을 요구한 이유는 혹여나 무한 스크롤이 돌아가고 있을때, 서버에서 값을 받기를 대기하고 있을지도 모를것 같아 개선 요청드립니다. 👍 
## Environment
iphone 11
Version : 1.1.0(38)

## Image
![IMG_3524](https://github.com/user-attachments/assets/3c5ee5e1-3dc1-44f2-b9f8-615011884eb0)

**Comment by jeongHunE** [comment]
1.1.0 beta 3에서 수정 완료
